
# Configuration file for MimicOS using ReserveTHP allocator with 32GB memory
# This configuration sets up the memory allocator to use the ReserveTHP policy with a total kernel memory size of 32GB
# The total memory size is set to 128GB, with a maximum order of 12 (4MB pages)
# The fragmentation type is set to largepage, and the threshold for promotion is set to 0.0 to allow immediate promotion of pages

[allocator]
memory_allocator=reserve_thp
max_order = 12

[pmem_alloc]
memory_size = 131072
target_fragmentation = 1.0
target_memory = 0.0
fragmentation_file = ""
kernel_size = 32768
max_order = 12
frag_type = largepage
threshold_for_promotion= 1.1

