

vm_scan: vm_scan.c
	gcc -o vm_scan vm_scan.c 
	@echo "Compilation complete. Run ./vm_scan to execute the program."
	@echo "To clean up, run 'make clean'."

hog_memory: hog_memory.c
	gcc -o hog_memory hog_memory.c 
	@echo "Compilation complete. Run ./hog_memory to execute the program."
	@echo "To clean up, run 'make clean'."

clean:
	rm -f vm_scan
	@echo "Cleaned up the compiled files."
	@echo "To compile again, run 'make vm_scan'."